### ISSUE TITLE
你好，请问x230i目前可以完美黑苹果么

### ISSUE THREAD

**Issue by ikx12333** [fivestrong/Hackintosh-X230i-macOS#1]
想了解一下目前该笔记本安装黑苹果还有什么方面的问题

**Comment by fivestrong** [comment]
> 想了解一下目前该笔记本安装黑苹果还有什么方面的问题

系统停留在了macOS 10.14.6 再没有升级过，目前没什么问题。
wifi 原生的不能用，需要更换在联想白名单上的，更换后没问题。
蓝牙使用的是电脑自带的，能够正常驱动，但是不确定是不是原厂的。
硬盘更换了三星的mSATA 不确定其他ssd或者机械硬盘能否启动（可能需要添加其他驱动到efi）。

其他的声音，usb(定制一下或者使用通用都没问题)，触摸板，显卡都能正常驱动。

一般影响黑苹果安装的就是硬盘是否兼容，显卡是否驱动。只要能够正常安装系统，并成功启动，剩下的网卡，声卡之类的就是小问题了。

**Comment by ikx12333** [comment]
好的， 感谢告知，谢谢

**Comment by fyj3344** [comment]
唯一不完美的就是wifi没有安装成功
